apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  namespace: jak-cd-dev
  labels:
    app: sa-logic
spec:
  selector:
     matchLabels:
       app: sa-logic
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      imagePullSecrets:
      - name: harborcred
      containers:
        - image: harbor.devopsdoor.com/jakdev/sa-logic:1.0.3
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
